@extends('layouts.master')
@section('title', 'Terms Of Use')
@section('content')
<div class="container container-body">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="{{ URL::to('/')}}">Home</a></li>
            <li class="active">Terms Of Service</li>
        </ol>
    </div>
    <div class="row">
        <h2 class="text-center primary-color">TERMS OF SERVICE</h2>
        <ol>
<li><strong><strong>GENERAL</strong></strong></li>
</ol>
<p>&ldquo;www.buddhijeevi.com&rdquo; (hereinafter, the &lsquo;Website&rsquo;) is owned and operated by BuddhiJeevi Private Limited (hereinafter the &lsquo;Company&rsquo;), a company formed as per the laws of India having its registered office at E-117, Brigade Courtyard, HMT Main Road, Jalahalli, Bangalore, Karnataka, India &ndash; 560013.</p>
<p><em><em>You are advised to read and understand these Terms carefully as moving past the home page, or using any of the services shall be taken to mean that You have read and agreed to all of the policies, which constitute a legally binding agreement between you and the Company. These terms are to be read along with the Privacy Policy and any other policies on the Website.</em></em>&nbsp;</p>
<p>This document is an electronic record under the laws of India which require publishing of Rules and Regulations, Privacy Policy and Terms of Service for access or usage of the Website and being generated by a computer system, it does not require any physical or digital signatures.</p>
<ol start="2">
<li><strong><strong>DEFINITIONS</strong></strong></li>
</ol>
<p>&ldquo;<strong><strong>We</strong></strong>&rdquo;, &ldquo;<strong><strong>Us</strong></strong>&rdquo;, &ldquo;<strong><strong>Our</strong></strong>&rdquo;, &ldquo;<strong><strong>BuddhiJeevi</strong></strong>&rdquo;, shall mean the Company.</p>
<p>&ldquo;<strong><strong>Terms</strong></strong>&rdquo;, &ldquo;<strong><strong>Terms and conditions</strong></strong>&rdquo;, &ldquo;<strong><strong>Policy</strong></strong>&rdquo;, &ldquo;<strong><strong>T&amp;C</strong></strong>&rdquo; shall mean the entire Agreement and all parallel policies that you agree to in mutual agreement by using our Site</p>
<p>&ldquo;<strong><strong>You</strong></strong>&rdquo;, &ldquo;<strong><strong>Your</strong></strong>&rdquo;, &ldquo;<strong><strong>User</strong></strong>&rdquo; refers to the user of the site. &ldquo;<strong><strong>User</strong></strong>&rdquo; is anyone who is visiting, accessing or browsing the Site.</p>
<p><strong><strong>&ldquo;Website&rdquo; </strong></strong>shall mean www.buddhijeevi.com, a Website through which the Company&rsquo;s services shall be availed.</p>
<p><strong><strong>&ldquo;Student&rdquo;</strong></strong>&nbsp;shall mean any user seeking knowledge or services with regard to obtaining knowledge on the Website</p>
<p><strong><strong>&ldquo;Institute&rdquo;, &ldquo;Trainer&rdquo; </strong></strong>shall mean any user seeking to impart knowledge to Students on the Website</p>
<p>&ldquo;<strong><strong>Content</strong></strong>&rdquo; refers to any text, image, graphic, video, audio, location or all forms of data which are made available on the Website, www.buddhijeevi.com</p>
<p>&ldquo;<strong><strong>Your Content</strong></strong>&rdquo; refers to any content submitted by way of registration or interaction by means of publishing or uploading content on the Site.</p>
<p>&ldquo;<strong><strong>Third Party</strong></strong>&rdquo; refers to any person other than the &ldquo;User&rdquo;, &ldquo;Company&rdquo; or the &ldquo;Website&rdquo;.</p>
<p><strong><strong>&ldquo;Affiliate(s)&rdquo;</strong></strong>&nbsp;refers to any Third Party that is, but is not limited to being, an Association Body, Self Help Group, Non-Government Organization, Sector Skill Councils, State Ministry and/or Central Ministry.&nbsp;</p>
<ol start="3">
<li><strong><strong>ABOUT BUDDHIJEEVI.COM</strong></strong></li>
</ol>
<p>The Website is primarily for any user (Hereinafter &lsquo;BuddhiJeevi <strong><strong>Members</strong></strong>&rsquo;) who would like to provide or avail of educational services. The Service aims at helping BuddhiJeevi Members access knowledge with ease, by being provided a learning community market platform in order to connect with someone who provides the desired knowledge.</p>
<p>The Service includes facilitating and hosting courses in batches, providing supporting materials, and taking feedback from BuddhiJeevi Members.</p>
<br>
<h4><strong><strong>Eligibility and Access For a Registered Member:</strong></strong></h4>
<p>Members must register with the Company to avail its services, and he/she would have to register by providing certain information, this information includes, but is not limited to, the following: Name, Phone Number, Email ID.</p>
<p>BuddhiJeevi will grant Members a Non-Transferrable Login rights through the information provided is a fully responsible for confidentiality, conduct, control or consequence of misuse by self or any other individual.</p>
<p>The Company may further, in its discretion terminate or end the relationship with any User with or without furnishing reasons for the same after settling all dues.&nbsp;</p>
<ol start="4">
<li><strong><strong>MEMBERSHIP</strong></strong></li>
</ol>
<p><strong><strong>For a Student:</strong></strong></p>
<ul>
<li>User must first register on the Website by providing his/her Name, Email ID and Phone Number.</li>
<li>Thereafter, the User can as per his/her discretion update his/her Profile Information by providing his/her educational background, experience, work expertise and concurrent skill sets.</li>
</ul>
<p><strong><strong>For Institutes and Trainers:</strong></strong></p>
<ul>
<li>User must first register on the Website by providing his/her Name, Email ID, Phone Number, Address and Location.</li>
<li>Thereafter, the User can as per his/her discretion update his/her Profile Information by providing his/her educational background, experience, work expertise and concurrent skill sets.</li>
<li>Thereafter, the User must enter a subscription model or any other pricing model (of those provided by the Website) with the Website as per his/her choice.&nbsp;</li>
</ul>
<p>At any time during Your use of this Website, including but not limited to the time of registration, You are solely responsible for protecting the confidentiality of Your username and password, and any activity under the account shall be deemed to have been done by You. BuddhiJeevi also encourages the user to provide other information such as Address, Education Information, Skillset, Work Experience and other identity information such as Voter ID, Aadhaar etc., Providing this information is completely voluntary and is meant to facilitate Members with benefits with government and corporate schemes. We encourage the member to provide us with accurate information. &nbsp;</p>
<p>In the case that You provide Us with false and/or inaccurate details or the Company has reason to believe you have done so, we hold the right to permanently suspend Your account.&nbsp;</p>
<ol start="5">
<li><strong><strong>PRIVACY POLICY</strong></strong></li>
</ol>
<p>The Privacy Policy is separately available on the Website, and can be perused by you at your convenience by looking <u><a href="{{URL::to('/privacy-policy')}}">here</a></u><u>.</u></p>
<ol start="6">
<li><strong><strong>CONTENT ON THE WEBSITE</strong></strong></li>
</ol>
<p>You agree, undertake and confirm that your use of our service shall be strictly governed by the following binding principles:</p>
<p>You agree and understand that the Website merely provides a learning community market place, and is in no manner responsible or liable for the User&rsquo;s interaction with each other and the services rendered by Users.&nbsp;</p>
<p>&nbsp;</p>
<p><strong><strong>USER&rsquo;S OBLIGATIONS</strong></strong></p>
<p>The User undertakes to fulfil the following obligations. Failure to satisfy any of these obligations gives Us the right to permanently suspend Your account and/or claim damages for any losses that accrue to Us or additional costs that may be imposed on us.</p>
<ol>
<li>You agree to comply with all local laws and regulations governing the downloading, installation and/or use of the Website, including, without limitation, any usage rules set forth in this Agreement.</li>
<li>If you are a Trainer and/or Institute, you understand and agree that you are contracting directly with BuddhiJeevi.com Pvt. Ltd in India, and that additionally, we may use our affiliate channel partners and subsidiaries to facilitate your payments, though your contract will remain between You and BuddhiJeevi.com</li>
<li>If you are a Trainer and/or Institute, you understand and agree that you will indemnify BuddhiJeevi.com for any issue arising out of your relationship with Students or your use of any Student related data.</li>
<li>If you are a Trainer and/or Institute, you understand and agree that you shall have and ensure all the required Infrastructure and Resources are made available to conduct the Classroom Training and maintain a conducive environment for a Training (that includes both Theory and practical) to take place.</li>
<li>You understand and agree that you hereby grant BhuddiJeevi.com a non-exclusive right and licence to reproduce, distribute, publicly perform, offer, market and otherwise use the submitted content through the Services, and sublicense it to the Users for these purposes directly or through third parties that can be used for marketing, promoting demonstrating or operating the services.</li>
<li>You understand and agree that the content submitted by you are governed by the Quality Control Processes we implement and agree to support us in our correspondence with you to abide to the changes we recommend.</li>
<li>You understand and agree that you are to not publish or teach the content that is restricted. Restricted contents include, but are not limited to, sexually explicit content, content relating to the making, handling or using of weapons, violence, hate Speech, enabling illegal behaviour, content that is intentionally misleading or deceiving or harmful to any party, offensive or otherwise inappropriate content or teaching.</li>
<li>You undertake not to:</li>
</ol>
<ol>
<li>Cut, copy, distribute, modify, recreate, reverse engineer, distribute, disseminate post, publish or create derivative works from, transfer, or sell any information or software obtained from the Website. For the removal of doubt, it is clarified that unlimited or wholesale reproduction, copying of the content for commercial or non-commercial purposes and unwarranted modification of data and information within the content of the Website is not permitted. Should You want to engage in one or more such actions, prior permission from Us must be obtained.</li>
<li>access (or attempt to access) the Website and/or the materials or Services by any means other than through the interface that is provided by the Website. The use of deep-link, robot, spider or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website or Content, or in any way reproduce or circumvent the navigational structure or presentation of the Website, materials or any Content, to obtain or attempt to obtain any materials, documents or information through any means not specifically made available through the Website is prohibited. You acknowledge and agree that by accessing or using the Website or Services, You may be exposed to content from other Users or Third Parties that You may consider offensive, indecent or otherwise objectionable. We disclaim all liabilities arising in relation to such offensive content on the Website. Further, You may report such offensive content.</li>
</ol>
<ul>
<li>use the Website in any manner that may impair, overburden, damage, disable or otherwise compromise (i) Company&rsquo;s services; (ii) any other party's use and enjoyment of company&rsquo;s services; or (iii) the services and products of any Third Party (including, without limitation, the Authorized Device).</li>
</ul>
<ol>
<li>use the Services or Materials for any unlawful purposes or to conduct any unlawful activity, including, but not limited to, fraud, embezzlement, money laundering or identity theft</li>
<li>abuse, harass, threaten, defame, disillusion, erode, abrogate, demean or otherwise violate the legal rights of others;</li>
<li>engage in any activity that interferes with or disrupts access to the Website or the Services (or the servers and networks which are connected to the Website);</li>
</ol>
<ul>
<li>upload or distribute files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of the Website or another's electronic device;</li>
<li>download any file posted in the Website that you know, or reasonably should know, cannot be legally distributed in such manner;</li>
</ul>
<ol>
<li>probe, scan or test the vulnerability of the Website, or any network connected to the Website, nor breach the security or authentication measures on the Website, or any network connected to the Website. You may not reverse look-up, trace or seek to trace any information on any other user, of or visitor to, the Website, or exploit the Website, or Service or information made available or offered by or through the Website, in any way whether or not the purpose is to reveal any information, including but not limited to personal identification information, other than Your own information, as provided for by the Website;</li>
<li>disrupt or interfere with the security of, or otherwise cause harm to, the Website, systems resources, &nbsp;servers or networks connected to or accessible through the Website, or any affiliated or linked Websites and/or Applications;</li>
<li>use the Website, or any material or Content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of this Website, or other Third Parties;</li>
</ol>
<ul>
<li>violate any applicable laws or regulations for the time being in force within or outside India;</li>
<li>violate any code of conduct or other guidelines, which may be applicable for or to any particular Service;</li>
<li>threaten the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.</li>
</ul>
<ol>
<li>disseminate information through the Website that is false, inaccurate or misleading, or violate any applicable laws or regulations for the time being in force in or outside India;
<ol>
<li>You understand and agree that the Website and the Company are not liable for any injuries, losses or disputes of any manner that arise between the Users of the Website.</li>
<li>You understand and agree that the Company owns and operates the Website as a learning community market place and is not liable for the interactions between the Users.</li>
<li>You understand and agree that BuddhiJeevi grants the student with limited and non-transferrable, non-exclusive licence to access and use submitted content and Company content to Student, solely for personal, non-commercial, and educational purpose through the Services offered through BuddhiJeevi.com platform.</li>
<li>If you are a Students, you understand and agree that Trainers/Institutes from whom Students may have purchased or Enrolled for Course(s) may choose to terminate their Accounts with BuddhiJeevi and become inactive. BuddhiJeevi does not guarantee Trainer/Institute availability to Students and shall not be held liable for any issues relating to Trainer/Institute availability.&nbsp;</li>
</ol>
</li>
</ol>
<ol start="7">
<li><strong><strong>PRICING AND PAYMENT</strong></strong></li>
</ol>
<p><strong><strong>Institutes and Trainers: </strong></strong></p>
<p>As an Institute and Trainers, you will be responsible for selecting the Base Price for the Courses/Batches you publish. The Price you set is under your own discretion, however, must be equal to or lower than the market price of the relevant Courses/Batches. You can promote your courses by providing discounts against the Batches by specifying a Unique Discount Code that can be used by a student in order to avail the same. You will not charge a student separately for any other downloadable content or<sup>&nbsp;</sup>Third Party links you embed or use in your course description. The Base Price is applicable for one-time enrolment into that Batch for the duration specified. BuddhiJeevi currently will not currently be involved in the payments, however, we may choose to do so at any time as per the Company&rsquo;s discretion and we shall update you on Policies regarding Online Payment methods that the Company has made available. The collection of payment shall be made either by the Company or by Trainers and/or Institutes as decided from time to time at the sole discretion of the Company.</p>
<p>Free Courses: For the Courses which you have marked as Free, you will not charge a student anything against the Registration, Admission and Enrolment fees. However, you are eligible to charge them on the Taxes as per the applicable tax laws of India. <br />If you are promoting the Training Course/Batches of a Government and/or a Corporate Training program or Scheme, you must have all legal permissions from the relevant intended authorities in promoting that program as per their Terms and conditions, Eligibility Criteria and Scheme/Programme Guidelines. You hereby indemnify BuddhiJeevi.com against any losses, injuries, issues and/or legal claims and/or actions arising out of you not having such permission, and BuddhiJeevi.com is not responsible whatsoever for the implications or penalties from the relevant intended authorities.</p>
<p>Subscription Fees: You agree to make payments on time regarding the Subscription fees or other fees to BuddhiJeevi.com based on the pricing model you have selected with us at the time of agreement/subscription.&nbsp;</p>
<p><strong><strong>Students: </strong></strong></p>
<p>The Student shall choose enrolment based on various factors: We encourage students to do due-diligence and research while making a choice for enrolment against a Training Course/Batch. You hereby agree to pay the fees (with applicable taxes), for the course that you choose, directly to the Training Institute. We encourage you to familiarize yourself with the Institute, Course and the facilities before deciding on the enrolling in the same and thereafter making a payment. The Company is not responsible for any dispute that may arise between You and any Trainer/Institute, and You shall solve such disputes directly with the Training Institute/Trainer, and hereby indemnify BuddhiJeevi.com against any losses, injuries, issues and/or legal claims and/or actions arising out of the same.</p>
<p>Browsing and the use of this Website is free of cost.</p>
<p>However, the Company shall charge Members for the services made available to them on the Website. These charges will be based upon the pricing model the Trainer/Institute chooses to follow, which include, but are not limited to, subscription, lead and listing based pricing. The Company can introduce different pricing models, or make changes to the pricing models currently made available, at any time as per its sole discretion. Further, Users rendering Services may or may not charge for said services as per their own discretion.<strong><strong>&nbsp;</strong></strong></p>
<ol start="8">
<li><strong><strong>REFUNDS</strong></strong></li>
<li>All payments that are due by the Institute/Trainer to the Company shall be made on an immediate basis and will not be refundable.</li>
<li>After rendering of the service to the Student, a Student may lodge a complaint to the Institute/Trainer as well as to the Company for deficiency of service. BuddhiJeevi.com may intervene to resolve the dispute but will not take any responsibility or guarantee of any refund. Any disputes regarding refunds should be settled between the Student and Institute/. &nbsp;</li>
</ol>
<ol start="9">
<li><strong><strong>TAXES</strong></strong></li>
</ol>
<p>The User takes full responsibility for payment of all taxes and fees that are levied or arise in the course of use of the Website.<strong><strong>&nbsp;</strong></strong></p>
<ol start="10">
<li><strong><strong>TERM AND TERMINATION</strong></strong></li>
<li>These Terms will remain in full force and effect while you are a User of the Website.</li>
<li>You may cease to be a User at any time, for any reason, effective upon receipt by the Company of your written or email notice of termination, sent to the postal or e-mail address.</li>
<li>The Website may at any time by giving you reasonable notice, terminate the agreement with you, deny you access to the Website and/or delete your Profile and/or any content you have submitted on the Website.</li>
<li>The Website may immediately terminate the agreement with you, deny you access to the Website and delete your Profile and any other Content you have submitted on the Website in the event that you have breached these Terms. In the event of such termination no refund shall be payable by the Company.</li>
</ol>
<p>&nbsp;</p>
<ol start="11">
<li><strong><strong>DISCLAIMER OF WARRANTY &amp; LIMITATIONS OF LIABILITY</strong></strong></li>
</ol>
<p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:</p>
<p>THE WEBSITE, SERVICES AND OTHER MATERIALS PROVIDED BY THIS WEBSITE ARE ON AN "AS IS" BASIS WITHOUT WARRANTY OF ANY KIND, EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING THE IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. WITHOUT LIMITING THE FOREGOING, THE COMPANY MAKES NO WARRANTY THAT</p>
<p>a.&nbsp;YOUR REQUIREMENTS WILL BE MET OR THAT SERVICES PROVIDED WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE;</p>
<p>b.&nbsp;MATERIALS, INFORMATION AND RESULTS OBTAINED WILL BE EFFECTIVE, ACCURATE OR RELIABLE;</p>
<p>c.&nbsp;ANY ERRORS OR DEFECTS IN THE WEBSITE, SERVICES OR OTHER MATERIALS WILL BE CORRECTED TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WE WILL HAVE NO LIABILITY RELATED TO USER CONTENT ARISING UNDER INTELLECTUAL PROPERTY RIGHTS, LIBEL, PRIVACY, PUBLICITY, OBSCENITY OR OTHER LAWS. THE COMPANY ALSO DISCLAIMS ALL LIABILITY WITH RESPECT TO THE MISUSE, LOSS, MODIFICATION OR UNAVAILABILITY OF ANY USER CONTENT.THE USER UNDERSTANDS AND AGREES THAT ANY MATERIAL OR DATA DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE WEBSITE IS DONE ENTIRELY AT HIS/HER OWN DISCRETION AND RISK AND HE/SHE WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO HIS/HER ELECTRONIC SYSTEMS OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF SUCH MATERIAL OR DATA. WE ARE NOT RESPONSIBLE FOR ANY TYPOGRAPHICAL ERROR LEADING TO AN INVALID COUPON. THE COMPANY ACCEPTS NO LIABILITY FOR ANY ERRORS OR OMISSIONS, WITH RESPECT TO ANY INFORMATION PROVIDED TO YOU WHETHER ON BEHALF OF ITSELF OR THIRD PARTIES.</p>
<p>WE SHALL NOT BE LIABLE FOR ANY THIRD PARTY PRODUCT OR SERVICES. THE ADVERTISEMENT AVAILABLE ON E-MAIL, WEBSITE OR WEBSITE WITH RESPECT TO THE THIRD PARTY WEBSITE OR THE PRODUCTS AND SERVICES ARE FOR INFORMATION PURPOSE ONLY.&nbsp;</p>
<ol start="12">
<li><strong><strong>INDEMNIFICATION </strong></strong></li>
</ol>
<p>YOU AGREE TO INDEMNIFY, DEFEND AND HOLD HARMLESS THIS COMPANY INCLUDING BUT NOT LIMITED TO ITS AFFILIATE VENDORS, AGENTS AND EMPLOYEES FROM AND AGAINST ANY AND ALL LOSSES, LIABILITIES, CLAIMS, DAMAGES, DEMANDS, COSTS AND EXPENSES (INCLUDING LEGAL FEES AND DISBURSEMENTS IN CONNECTION THEREWITH AND INTEREST CHARGEABLE THEREON) ASSERTED AGAINST OR INCURRED BY US THAT ARISE OUT OF, RESULT FROM, OR MAY BE PAYABLE BY VIRTUE OF, ANY BREACH OR NON-PERFORMANCE OF ANY REPRESENTATION, WARRANTY, COVENANT OR AGREEMENT MADE OR OBLIGATION TO BE PERFORMED BY YOU PURSUANT TO THESE TERMS OF SERVICE. FURTHER, YOU AGREE TO HOLD US HARMLESS AGAINST ANY CLAIMS MADE BY ANY THIRD PARTY DUE TO, OR ARISING OUT OF, OR IN CONNECTION WITH, YOUR USE OF THE WEBSITE, ANY CLAIM THAT YOUR MATERIAL CAUSED DAMAGE TO A THIRD PARTY, YOUR VIOLATION OF THE TERMS OF SERVICE, OR YOUR VIOLATION OF ANY RIGHTS OF ANOTHER, INCLUDING ANY INTELLECTUAL PROPERTY RIGHTS.</p>
<p>IN NO EVENT SHALL THE COMPANY, ITS OFFICERS, DIRECTORS, EMPLOYEES, PARTNERS OR SUPPLIERS BE LIABLE TO YOU, THE FREIGHT FORWARDER OR ANY THIRD PARTY FOR ANY SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL OR PUNITIVE DAMAGES WHATSOEVER, INCLUDING THOSE RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER OR NOT FORESEEABLE OR WHETHER OR NOT WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, OR BASED ON ANY THEORY OF LIABILITY, INCLUDING BREACH OF CONTRACT OR WARRANTY, NEGLIGENCE OR OTHER TORTIOUS ACTION, OR ANY OTHER CLAIM ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF OR ACCESS TO THE WEBSITE, SERVICES OR MATERIALS.</p>
<h4>THE LIMITATIONS AND EXCLUSIONS IN THIS SECTION APPLY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW.&nbsp;</h4>
<ol start="13">
<li><strong><strong>GOVERNING LAW</strong></strong></li>
</ol>
<p>In the unlikely event we end up in a legal dispute, it will take place in the Bangalore courts, applying Indian law.&nbsp;</p>
<p>You agree that the laws of the State of Karnataka, India, excluding its conflict of laws rules, shall exclusively govern any dispute relating to this Agreement and/or the Services. We both agree that all of these claims can only be litigated in the courts of Bangalore and we each agree to personal jurisdiction in those courts.</p>
<ol start="14">
<li><strong><strong>INTELLECTUAL PROPERTY RIGHTS</strong></strong>
<ol>
<li>All information, content, services and software displayed on, transmitted through, or used in connection with the Website, including for example news articles, reviews, directories, guides, text, photographs, images, illustrations, audio clips, video, html, source and object code, trademarks, logos, and the like (collectively and hereinafter referred to as the "Content"), as well as its selection and arrangement, is owned by Us. You may use the Content only through the Website, and solely for your personal, non-commercial use.</li>
<li>You may not, republish any portion of the Content on any Internet, Intranet or extranet site or incorporate the Content in any database, compilation, archive or cache. You may not distribute any Content to others, whether or not for payment or other consideration, and you may not modify, copy, frame, cache, reproduce, sell, publish, transmit, display or otherwise use any portion of the Content. You may not scrape or otherwise copy our Content without permission. You agree not to decompile, reverse engineer or disassemble any software or other products or processes accessible through the Website, not to insert any code or product or manipulate the content of the Website in any way that affects the user's experience, and not to use any data mining, data gathering or extraction method.</li>
<li>All content uploaded, transmitted or posted to the Services by a User is "Your Content". Content remains the proprietary property of the person or entity supplying it (or their affiliated and/or third party providers and suppliers) and is protected, without limitation, pursuant to Indian and foreign copyright and other intellectual property laws. You hereby represent and warrant that You have all licenses, rights, consents, and permissions necessary to grant the rights set forth in these Terms to BuddhiJeevi with respect to Your Submitted Content and that BuddhiJeevi shall not need to obtain any licenses, rights, consents, or permissions from, or make any payments to, any third party for any use or exploitation of Your Submitted Content as authorized in these Terms or have any liability to You or any other party as a result of any use or exploitation of Your Submitted Content as authorized in these Terms.</li>
<li>In the event of Termination, the &nbsp;User is solely responsible to clear his/her content at the time of termination of contract or suspension; BuddhiJeevi is not responsible for the loss of any content thereafter. &nbsp;<strong><strong>&nbsp;</strong></strong></li>
</ol>
</li>
</ol>
<ol start="15">
<li><strong><strong>ASSIGNMENT</strong></strong></li>
</ol>
<p>&nbsp;You agree that the Company, automatically assigns this Agreement and information incorporated herein in to a User. You may not assign your obligations under these terms to another entity.</p>
<ol start="16">
<li><strong><strong>MISCELLANEOUS TERMS</strong></strong></li>
<li><strong><em><strong><em>Independent Contractors: </em></strong></em></strong>The Company is not an agent, employee or partner of the User, that is of the Students, Institutes of Trainers and simply provides a learning community market place..</li>
<li><strong><em><strong><em>Modification of the Terms of Service: </em></strong></em></strong>These terms of service may be modified from time to time to deliver better services or to intimate Users of the modified terms. It shall be the obligation of the User to acquaint himself or herself with the modified Terms of Service from going to the Website and reading the terms of service from time to time. The Company agrees to inform the User either through email or a pop up on the main page if there have been any significant changes made to the terms of usage on the Website.</li>
<li><strong><em><strong><em>Waiver: </em></strong></em></strong>A decision not to act against any User for any improper conduct does not prevent the Company from acting in any future case against the same or other Users.</li>
<li><strong><em><strong><em>Severability: </em></strong></em></strong>Any portion of this Agreement held unenforceable by a Court of law shall not affect the operation of any other portion of the Agreement, and the rest of the Agreement shall be read in such a way as to be compliant with all applicable laws.</li>
<li><strong><em><strong><em>Dispute Resolution</em></strong></em></strong><em><em>: </em></em>All disputes will be resolved amicably by mediation or negotiation, following which they shall be referred to arbitration, as per the Arbitration and Conciliation Act, 1996. The seat of the arbitral proceedings shall be Bangalore and the venue of the same shall be Bangalore. The matter shall be referred to a sole arbitrator as selected by Company. &nbsp;The arbitral award shall be final and binding on both parties.</li>
<li><strong><strong>CONTACT US</strong></strong></li>
</ol>
<p>If you have any questions about this Agreement, the practices of the Company, or your experience with the Website, you can e-mail us at <a href="mailto:operations@buddhijeevi.com"><u>operations@buddhijeevi.com</u></a></p>
<p>&nbsp;</p>
<h6><em><em>&nbsp;</em></em></h6>
<p>&nbsp;</p>
    </div>
</div>
@endsection